// <auto-generated />
using System;
using System.Collections.Generic;
using AlGreenMES.Modules.Production.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlGreenMES.Modules.Production.Infrastructure.Migrations
{
    [DbContext(typeof(ProductionDbContext))]
    partial class ProductionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("production")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlGreenMES.Modules.Production.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<decimal?>("DimensionX")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("dimension_x");

                    b.Property<decimal?>("DimensionY")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("dimension_y");

                    b.Property<decimal?>("DimensionZ")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("dimension_z");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("max_quantity");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("min_quantity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_materials");

                    b.HasIndex("TenantId", "Category")
                        .HasDatabaseName("ix_materials_tenant_id_category");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_materials_tenant_id_code");

                    b.ToTable("materials", "production");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Production.Domain.Entities.Process", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_order");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_processes");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_processes_tenant_id_code");

                    b.ToTable("processes", "production");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Production.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int?>("DefaultCriticalDays")
                        .HasColumnType("integer")
                        .HasColumnName("default_critical_days");

                    b.Property<int?>("DefaultWarningDays")
                        .HasColumnType("integer")
                        .HasColumnName("default_warning_days");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_product_categories");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_product_categories_tenant_id_name");

                    b.ToTable("product_categories", "production");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Production.Domain.Entities.ProductCategoryDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DependsOnProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("depends_on_process_id");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_category_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_product_category_dependencies");

                    b.HasIndex("DependsOnProcessId")
                        .HasDatabaseName("ix_product_category_dependencies_depends_on_process_id");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_product_category_dependencies_process_id");

                    b.HasIndex("ProductCategoryId", "ProcessId", "DependsOnProcessId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_category_dependencies_product_category_id_process_i");

                    b.ToTable("product_category_dependencies", "production");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Production.Domain.Entities.ProductCategoryProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultComplexity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_complexity");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_category_id");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_product_category_processes");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_product_category_processes_process_id");

                    b.HasIndex("ProductCategoryId", "ProcessId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_category_processes_product_category_id_process_id");

                    b.ToTable("product_category_processes", "production");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Production.Domain.Entities.SpecialRequestType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<Guid>>("AddsProcesses")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("adds_processes");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IgnoresDependencies")
                        .HasColumnType("boolean")
                        .HasColumnName("ignores_dependencies");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<Guid>>("OnlyProcesses")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("only_processes");

                    b.PrimitiveCollection<List<Guid>>("RemovesProcesses")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("removes_processes");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_special_request_types");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_special_request_types_tenant_id_code");

                    b.ToTable("special_request_types", "production");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Production.Domain.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DocumentReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_reference");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("movement_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_price");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_movements");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_stock_movements_material_id");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_stock_movements_process_id");

                    b.HasIndex("TenantId", "DocumentReference")
                        .HasDatabaseName("ix_stock_movements_tenant_id_document_reference");

                    b.HasIndex("TenantId", "MaterialId")
                        .HasDatabaseName("ix_stock_movements_tenant_id_material_id");

                    b.HasIndex("TenantId", "MovementDate")
                        .HasDatabaseName("ix_stock_movements_tenant_id_movement_date");

                    b.ToTable("stock_movements", "production");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Production.Domain.Entities.SubProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_order");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_sub_processes");

                    b.HasIndex("ProcessId", "SequenceOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_sub_processes_process_id_sequence_order")
                        .HasFilter("is_active = true");

                    b.ToTable("sub_processes", "production");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Production.Domain.Entities.ProductCategoryDependency", b =>
                {
                    b.HasOne("AlGreenMES.Modules.Production.Domain.Entities.Process", "DependsOnProcess")
                        .WithMany()
                        .HasForeignKey("DependsOnProcessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_category_dependencies_processes_depends_on_process_");

                    b.HasOne("AlGreenMES.Modules.Production.Domain.Entities.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_category_dependencies_processes_process_id");

                    b.HasOne("AlGreenMES.Modules.Production.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Dependencies")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_category_dependencies_product_categories_product_ca");

                    b.Navigation("DependsOnProcess");

                    b.Navigation("Process");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Production.Domain.Entities.ProductCategoryProcess", b =>
                {
                    b.HasOne("AlGreenMES.Modules.Production.Domain.Entities.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_category_processes_processes_process_id");

                    b.HasOne("AlGreenMES.Modules.Production.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Processes")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_category_processes_product_categories_product_categ");

                    b.Navigation("Process");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Production.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("AlGreenMES.Modules.Production.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_materials_material_id");

                    b.HasOne("AlGreenMES.Modules.Production.Domain.Entities.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_movements_processes_process_id");

                    b.Navigation("Material");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Production.Domain.Entities.SubProcess", b =>
                {
                    b.HasOne("AlGreenMES.Modules.Production.Domain.Entities.Process", "Process")
                        .WithMany("SubProcesses")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sub_processes_processes_process_id");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Production.Domain.Entities.Process", b =>
                {
                    b.Navigation("SubProcesses");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Production.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Processes");
                });
#pragma warning restore 612, 618
        }
    }
}
