// <auto-generated />
using System;
using AlGreenMES.Modules.Orders.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlGreenMES.Modules.Orders.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20260510201316_AddOrderManualProcesses")]
    partial class AddOrderManualProcesses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orders")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.BlockRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlockReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("block_reason");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handled_at");

                    b.Property<Guid?>("HandledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("handled_by_user_id");

                    b.Property<Guid?>("OrderItemProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_process_id");

                    b.Property<Guid?>("OrderItemSubProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_sub_process_id");

                    b.Property<string>("RejectionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("rejection_note");

                    b.Property<string>("RequestNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("request_note");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_block_requests");

                    b.HasIndex("OrderItemProcessId")
                        .HasDatabaseName("ix_block_requests_order_item_process_id");

                    b.HasIndex("OrderItemSubProcessId")
                        .HasDatabaseName("ix_block_requests_order_item_sub_process_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_block_requests_tenant_id_status");

                    b.ToTable("block_requests", "orders");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.ChangeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handled_at");

                    b.Property<Guid?>("HandledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("handled_by_user_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("request_type");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("ResponseNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("response_note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_change_requests");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_change_requests_order_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_change_requests_tenant_id_status");

                    b.ToTable("change_requests", "orders");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notifications_user_id_is_read");

                    b.ToTable("notifications", "orders");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int?>("CustomCriticalDays")
                        .HasColumnType("integer")
                        .HasColumnName("custom_critical_days");

                    b.Property<int?>("CustomWarningDays")
                        .HasColumnType("integer")
                        .HasColumnName("custom_warning_days");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_date");

                    b.Property<bool>("IsInvoiced")
                        .HasColumnType("boolean")
                        .HasColumnName("is_invoiced");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("order_type");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("TenantId", "DeliveryDate")
                        .HasDatabaseName("ix_orders_tenant_id_delivery_date");

                    b.HasIndex("TenantId", "OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_tenant_id_order_number");

                    b.HasIndex("TenantId", "Priority")
                        .HasDatabaseName("ix_orders_tenant_id_priority");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_orders_tenant_id_status");

                    b.ToTable("orders", "orders");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid?>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stored_file_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_order_attachments");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_attachments_order_id");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("ix_order_attachments_order_item_id");

                    b.HasIndex("TenantId", "OrderId")
                        .HasDatabaseName("ix_order_attachments_tenant_id_order_id");

                    b.ToTable("order_attachments", "orders");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_category_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.ToTable("order_items", "orders");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderItemProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlockReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("block_reason");

                    b.Property<DateTime?>("BlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_at");

                    b.Property<Guid?>("BlockedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_by_user_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Complexity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("complexity");

                    b.Property<bool>("ComplexityOverridden")
                        .HasColumnType("boolean")
                        .HasColumnName("complexity_overridden");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsWithdrawn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_withdrawn");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<DateTime?>("ResumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resumed_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StoppedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stopped_at");

                    b.Property<Guid?>("StoppedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("stopped_by_user_id");

                    b.Property<string>("StoppedReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("stopped_reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("total_duration_minutes");

                    b.Property<DateTime?>("UnblockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unblocked_at");

                    b.Property<Guid?>("UnblockedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("unblocked_by_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.Property<Guid?>("WithdrawnByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("withdrawn_by_user_id");

                    b.Property<string>("WithdrawnReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("withdrawn_reason");

                    b.HasKey("Id")
                        .HasName("pk_order_item_processes");

                    b.HasIndex("OrderItemId", "ProcessId")
                        .IsUnique()
                        .HasDatabaseName("ix_order_item_processes_order_item_id_process_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_order_item_processes_tenant_id_status");

                    b.ToTable("order_item_processes", "orders");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderItemSpecialRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<Guid>("SpecialRequestTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("special_request_type_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_order_item_special_requests");

                    b.HasIndex("OrderItemId", "SpecialRequestTypeId")
                        .IsUnique()
                        .HasDatabaseName("ix_order_item_special_requests_order_item_id_special_request_t");

                    b.ToTable("order_item_special_requests", "orders");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderItemSubProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsWithdrawn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_withdrawn");

                    b.Property<Guid>("OrderItemProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_process_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("StoppedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("stopped_by_user_id");

                    b.Property<string>("StoppedReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("stopped_reason");

                    b.Property<Guid>("SubProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_process_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("total_duration_minutes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.Property<Guid?>("WithdrawnByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("withdrawn_by_user_id");

                    b.Property<string>("WithdrawnReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("withdrawn_reason");

                    b.HasKey("Id")
                        .HasName("pk_order_item_sub_processes");

                    b.HasIndex("OrderItemProcessId", "SubProcessId")
                        .IsUnique()
                        .HasDatabaseName("ix_order_item_sub_processes_order_item_process_id_sub_process_");

                    b.ToTable("order_item_sub_processes", "orders");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderItemSubProcessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("OrderItemSubProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_sub_process_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_order_item_sub_process_logs");

                    b.HasIndex("OrderItemSubProcessId")
                        .HasDatabaseName("ix_order_item_sub_process_logs_order_item_sub_process_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_order_item_sub_process_logs_user_id");

                    b.ToTable("order_item_sub_process_logs", "orders");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderManualProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DefaultComplexity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_complexity");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_order_manual_processes");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_manual_processes_order_id");

                    b.HasIndex("OrderId", "ProcessId")
                        .IsUnique()
                        .HasDatabaseName("ix_order_manual_processes_order_id_process_id");

                    b.ToTable("order_manual_processes", "orders");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderManualProcessDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("DependsOnProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("depends_on_process_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_order_manual_process_dependencies");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_manual_process_dependencies_order_id");

                    b.HasIndex("OrderId", "ProcessId", "DependsOnProcessId")
                        .IsUnique()
                        .HasDatabaseName("ix_order_manual_process_dependencies_order_id_process_id_depen");

                    b.ToTable("order_manual_process_dependencies", "orders");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderTypes.OrderType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsManualProcesses")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_manual_processes");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_order_types");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_order_types_tenant_id_code");

                    b.ToTable("order_types", "orders");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("P256dhKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("p256dh_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_subscriptions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_push_subscriptions_user_id");

                    b.HasIndex("UserId", "Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_push_subscriptions_user_id_endpoint")
                        .HasFilter("is_active = true");

                    b.ToTable("push_subscriptions", "orders");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.WorkSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_time");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_work_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_work_sessions_user_id");

                    b.HasIndex("TenantId", "Date")
                        .HasDatabaseName("ix_work_sessions_tenant_id_date");

                    b.ToTable("work_sessions", "orders");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.BlockRequest", b =>
                {
                    b.HasOne("AlGreenMES.Modules.Orders.Domain.Entities.OrderItemProcess", "OrderItemProcess")
                        .WithMany()
                        .HasForeignKey("OrderItemProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_block_requests_order_item_processes_order_item_process_id");

                    b.HasOne("AlGreenMES.Modules.Orders.Domain.Entities.OrderItemSubProcess", "OrderItemSubProcess")
                        .WithMany()
                        .HasForeignKey("OrderItemSubProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_block_requests_order_item_sub_processes_order_item_sub_proc");

                    b.Navigation("OrderItemProcess");

                    b.Navigation("OrderItemSubProcess");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.ChangeRequest", b =>
                {
                    b.HasOne("AlGreenMES.Modules.Orders.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_change_requests_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderAttachment", b =>
                {
                    b.HasOne("AlGreenMES.Modules.Orders.Domain.Entities.Order", "Order")
                        .WithMany("Attachments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_attachments_orders_order_id");

                    b.HasOne("AlGreenMES.Modules.Orders.Domain.Entities.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_order_attachments_order_items_order_item_id");

                    b.Navigation("Order");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("AlGreenMES.Modules.Orders.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderItemProcess", b =>
                {
                    b.HasOne("AlGreenMES.Modules.Orders.Domain.Entities.OrderItem", "OrderItem")
                        .WithMany("Processes")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_processes_order_items_order_item_id");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderItemSpecialRequest", b =>
                {
                    b.HasOne("AlGreenMES.Modules.Orders.Domain.Entities.OrderItem", "OrderItem")
                        .WithMany("SpecialRequests")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_special_requests_order_items_order_item_id");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderItemSubProcess", b =>
                {
                    b.HasOne("AlGreenMES.Modules.Orders.Domain.Entities.OrderItemProcess", "OrderItemProcess")
                        .WithMany("SubProcesses")
                        .HasForeignKey("OrderItemProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_sub_processes_order_item_processes_order_item_pr");

                    b.Navigation("OrderItemProcess");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderItemSubProcessLog", b =>
                {
                    b.HasOne("AlGreenMES.Modules.Orders.Domain.Entities.OrderItemSubProcess", "OrderItemSubProcess")
                        .WithMany("Logs")
                        .HasForeignKey("OrderItemSubProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_sub_process_logs_order_item_sub_processes_order_");

                    b.Navigation("OrderItemSubProcess");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderManualProcess", b =>
                {
                    b.HasOne("AlGreenMES.Modules.Orders.Domain.Entities.Order", null)
                        .WithMany("ManualProcesses")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_manual_processes_orders_order_id");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderManualProcessDependency", b =>
                {
                    b.HasOne("AlGreenMES.Modules.Orders.Domain.Entities.Order", null)
                        .WithMany("ManualProcessDependencies")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_manual_process_dependencies_orders_order_id");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.Order", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Items");

                    b.Navigation("ManualProcessDependencies");

                    b.Navigation("ManualProcesses");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderItem", b =>
                {
                    b.Navigation("Processes");

                    b.Navigation("SpecialRequests");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderItemProcess", b =>
                {
                    b.Navigation("SubProcesses");
                });

            modelBuilder.Entity("AlGreenMES.Modules.Orders.Domain.Entities.OrderItemSubProcess", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
